### ISSUE TITLE
merge from PhotoSlider

### ISSUE THREAD

**Issue by nakajijapan** [nakajijapan/NKJPhotoSliderController#19]
## Todo
- [x] [Autorotation Problem](https://github.com/nakajijapan/PhotoSlider/pull/17)
- [x] [Allows to get current page when controller was dismissed.](https://github.com/nakajijapan/PhotoSlider/pull/20)
- [x] [Allow to set custom page control.](https://github.com/nakajijapan/PhotoSlider/pull/22)
- [x] [Reset previous image zoom.](https://github.com/nakajijapan/PhotoSlider/pull/24)
- [x] [Image load from exist object](https://github.com/nakajijapan/PhotoSlider/pull/26)

**Comment by nakajijapan** [comment]
ok
